### ISSUE TITLE
Chinese text is messy code,how to resolve it

### ISSUE THREAD

**Issue by lhjandroid** [hydro-sdk/hydro-sdk#324]

**Comment by chgibb** [comment]
Hi @lhjandroid thanks for checking out Hydro! What version of Hydro-SDK are you using? What operating system? What devices?

**Comment by lhjandroid** [comment]
> Hi @lhjandroid thanks for checking out Hydro! What version of Hydro-SDK are you using? What operating system? What devices?

thanks for you reply. 
use this.
**package.json**
```
{
  "name": "testdemo",
  "version": "1.0.0",
  "description": "A new Flutter project.",
  "main": "index.js",
  "directories": {
    "lib": "lib",
    "test": "test"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@hydro-sdk/hydro-sdk": "0.0.1-nightly.21",
    "chokidar": "^3.5.1"
  },
  "devDependencies": {}
}
```
**and the pubspec.yaml**
```
name: testDemo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  hydro_sdk:
    git:
      ref: "0.0.1-nightly.21"
      url: "git://github.com/hydro-sdk/hydro-sdk.git"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - "assets/hello-world.hc"
    - "assets/hello-world.hc.sha256"
    - "assets/hello-world.hc.symbols"

```
**and my test code**
```
import { runApp } from "@hydro-sdk/hydro-sdk/runtime/flutter/runApp";
import { pauseInDebugger } from "@hydro-sdk/hydro-sdk/runtime/dart/developer/debugger";

import {
    StatelessWidget,
    Text,
    Container,
    Center,
    GestureDetector,
    SafeArea
} from "@hydro-sdk/hydro-sdk/runtime/flutter/widgets/index";

import { Colors, MaterialApp, Scaffold } from "@hydro-sdk/hydro-sdk/runtime/flutter/material/index";
import { Widget } from "@hydro-sdk/hydro-sdk/runtime/flutter/widget";
import { Color } from "@hydro-sdk/hydro-sdk/runtime/dart/ui/color";
import { TextStyle } from "@hydro-sdk/hydro-sdk/runtime/flutter/painting/textStyle";
import { double } from "@hydro-sdk/hydro-sdk/runtime/dart/core/double";

class MyWidget extends StatelessWidget {


    private a = 2222;

    public constructor() {
        super();
    }

    public build(): Widget {
        return new MaterialApp({
            home: new Scaffold({
                body: new SafeArea({
                    child: new Container({
                        width: double.infinity,
                        height: double.infinity,
                        color: new Color(0xFFFF4891),
                        child: new GestureDetector({
                            onTap: () => {
                                console.log("呵呵呵呵111")
                            },
                            child: new Center({
                                child: new Text("2222汉字444assss" + this.a, {
                                    style: new TextStyle({
                                        color: Colors.white
                                    })
                                })
                            })
                        })
                    })
                })
            })
        })
    }
}

runApp(() => new MyWidget());
```
Look forward to your favourable reply
